config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'events#index'
  resources :users, only: [:show]
  resources :memos, only: [:create]

  resources :events, only: [:index, :show] do
    resources :reaction_likes, only: [:create, :destroy]
  end
  namespace :admin do
    resources :events, only: [:new, :create, :destroy, :update, :edit]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comedian.rb
class Comedian < ActiveHash::Base
  include ActiveHash::Associations
  has_many :event_comedians
  has_many :events, through: :event_comedians

  self.data = [
    { id: 0, name: '' },
    { id: 1, name: '春風亭　太郎' },
    { id: 2, name: '柳家　次郎' },
    { id: 3, name: '橘　三郎' },
    { id: 4, name: '桂　四郎' },
    { id: 5, name: '三遊亭　五郎' },
    { id: 6, name: '神田　六郎' },
    { id: 7, name: '笑福亭　七郎' },
    { id: 8, name: '柳亭　八郎' },
    { id: 9, name: '五街道　九郎' },
    { id: 10, name: '桃月　十郎' }
  ]
end

app/models/daynight.rb
class Daynight < ActiveHash::Base
  include ActiveHash::Associations
  has_many :events

  self.data = [
    { id: 0, name: '' },
    { id: 1, name: '昼' },
    { id: 2, name: '夜' }
]
end

app/models/event.rb
class Event < ApplicationRecord
  include ActiveHash::Associations
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_many :users, through: :reaction_likes
  has_many :event_comedians, dependent: :destroy
  has_many :comedians, through: :event_comedians

  belongs_to :theater
  belongs_to :daynight

  has_many :reaction_likes
  #「誰が」いいねをしたのかを取得する
  has_many :reaction_liked_users, through: :reaction_likes, source: :user
end

app/models/event_comedian.rb
class EventComedian < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :comedian
  belongs_to :event
end

app/models/event_comedian_form.rb
class EventComedianForm
  include ActiveModel::Model
  include ActiveRecord::AttributeAssignment
  extend ActiveHash::Associations::ActiveRecordExtensions
#  attr_accessor :theater_id, :daynight_id, :start_time, :comedian_id, :comedian_ids
  attr_accessor :theater_id, :daynight_id, :start_time, :start_times, :comedian_id, :comedian_ids
  with_options presence: true do
    validates :theater_id
    validates :daynight_id
#    validates :start_time
  end

  def save(comedians)
    event = Event.create(theater_id: theater_id, daynight_id: daynight_id, start_time: start_time)
    i = 0
    comedians.each do |comedians|
      EventComedian.create(event_id: event.id, comedian_id: comedian_ids[i])
      i += 1
    end
  end

#  def save(comedians, start_times)
#    x = 0
#    start_times.each do |start_time|
#      event = Event.create(theater_id: theater_id, daynight_id: daynight_id, start_time: start_times[x])
#      i = 0
#      comedians.each do |comedians|
#        EventComedian.create(event_id: event.id, comedian_id: comedian_ids[i])
#        i += 1
#      end
#      x += 1
#    end
#  end

#  def update(comedians)
#    event = Event.update(theater_id: theater_id, daynight_id: daynight_id, start_time: start_time)
#    i = 0
#    comedians.each do |comedians|
#      EventComedian.update(event_id: event.id, comedian_id: comedian_ids[i])
#      i += 1
#    end
#  end
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :reaction_like
end

app/models/reaction_like.rb
class ReactionLike < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates_uniqueness_of :event_id, scope: :user_id
  #memoがネスト構造になるかも？
end

app/models/theater.rb
class Theater < ActiveHash::Base
  include ActiveHash::Associations
  has_many :events

  self.data = [
    { id: 0, name: '' },
    { id: 1, name: '新宿末廣亭' },
    { id: 2, name: '池袋演芸場' },
    { id: 3, name: '浅草演芸ホール' },
    { id: 4, name: '上野鈴本' }
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
  # passwordは半角英数字のバリデーション
  validates :encrypted_password, :password, :password_confirmation, format: { with: /(?=.*[a-zA-Z])(?=.*\d)[a-zA-Z\d]/ }

  has_many :events, through: :reaction_likes
  has_many :reaction_likes, dependent: :destroy
  # ユーザーがどの番組に「いいねをした」かを取得する
  has_many :reaction_liked_events, through: :reaction_likes, source: :event

  # ユーザーがすでにいいねをしているかどうかの判定をする。
  def already_reaction_liked?(event)
    self.reaction_likes.exists?(event_id: event.id)
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  #管理者ユーザー以外でアクションをしようとするとトップページに遷移する
  before_action :if_not_admin


  #管理者だけにさせたいアクションは以下に記述する！
  def new
    @event = EventComedianForm.new
  end

  def create
    @event = EventComedianForm.new(event_params)
    # 複数日付登録用の変数start_timesを作成
    #start_times = params[:event_comedian_form][:start_times]
    comedians = params[:event_comedian_form][:comedian_ids]
    if @event.valid?
      @event.save(comedians)
      #@event.save(comedians, start_times)
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @event = Event.find(params[:id])
  end
#
#  def update
#    @event = Event.find(params[:id])
#    comedians = params[:event_comedian_form][:comedian_ids]
#    binding.pry
#    if @event.valid?
#      @event.update(comedians)
#      redirect_to event_path(event.id)
#    else
#    render 'edit'
#    end
#  end

  #def destroy
  #  event = EventComedianForm.find(params[:id])
  #  event.destroy
  #end

  private
  def if_not_admin
    if user_signed_in?
      if current_user.admin != true
        redirect_to root_path
      end
    else
      redirect_to root_path
    end
  end

  def event_params
    params.require(:event_comedian_form).permit(:theater_id, :start_time, :daynight_id, comedian_ids: [])
#    params.require(:event_comedian_form).permit(:theater_id, start_times: [], :daynight_id, comedian_ids: [])
  end

  def event_update_params
    params.require(:event_comedian_form).permit(:theater_id, :start_time, :daynight_id, comedian_ids: [], event_id: params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
    @reaction_like = ReactionLike.new
  end

  def show
    @events = Event.all
    @show = Event.find(params[:id])
    # 対象の日付の全ての演芸場のデータを取得する
    @shows = Event.where(start_time: @show.start_time)
    @reaction_like = ReactionLike.new
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :authenticate_user!

  def new
    @memo = Memo.new
  end

  def create
    @memo = Memo.new(memo_params)
    if @memo.valid?
      @memo.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  private
  def memo_params
    params.require(:memo).permit(:text).merge(reaction_like_id: params[:reaction_like_id])
  end
end

app/controllers/reaction_likes_controller.rb
class ReactionLikesController < ApplicationController
  before_action :authenticate_user!
  def create
    @event = Event.find(params[:event_id])
    @reaction_like = ReactionLike.create(event_id: params[:event_id], user_id: current_user.id)
    redirect_back(fallback_location: root_path)
  end

  def destroy
    # findメソッドはidを引数に取る。find_byメソッドは属性を取り、複数条件を指定できる。
    @reaction_like = ReactionLike.find_by(event_id: params[:event_id], user_id: current_user.id)
    @reaction_like.destroy
    #直前のぺージにリダイレクトする。いいねを消したら、トップページをリダイレクトして反映させている
    redirect_back(fallback_location: root_path)
  end

  private
    def reaction_like_params
      params.require(:reaction_like).permit(:event_id, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = User.find(params[:id])
    @reaacton_like = ReactionLike.new
    @memo = Memo.new
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/reaction_likes_helper.rb
module ReactionLikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_asakusa.html.erb
<!-- 昼席の表示 -->
<div class="card col-12 yose-hiru">
    <div class="card-body text-box">
        <div class="card-text comedians">
            <% events.each do |event| %>
              <% if (event.start_time == Date.today) && (event.theater_id == 3) && (event.daynight_id == 1) %>
                <p class="yose-title"><%= event.theater.name %></p>
                <p class="yose-title"><%= event.daynight.name %>席</p>
                <%# 出演者の名前 %>
                <% event.event_comedians.each do |event_comedian| %>
                  <% if event_comedian.comedian_id != 0 %>
                    <div class="wood">
                      <%= image_tag("wood.jpg", class: "img-fluid") %>
                      <p class="comedian-name">
                        一．<%= event_comedian.comedian.name %>
                      </p>
                    </div>
                  <% end %>
                <% end %> <!-- 芸名表示のeachメソッド終わり -->
                <!-- いいねボタン表示 -->
                <% if user_signed_in? %>
                  <% if current_user.already_reaction_liked?(event) %>
                   <%= button_to 'いいね削除', event_reaction_like_path(event, current_user), method: :delete, class:"mr-1" %>
                  <% else %>
                   <%= button_to 'いいね', event_reaction_likes_path(event), method: :post, class:"mr-1" %>
                  <% end %>
                  <!-- 管理者のみ編集・削除ボタン -->
                  <% if current_user.admin == true %>
                    <%= button_to '編集', edit_admin_event_path(event), method: :get, class:"mr-1" %>
                    <%= button_to '削除', admin_event_path(event), method: :delete, class:"mr-1" %>
                  <% end %>
                <% end %>
              <% end %> <!-- 昼席のif指定終わり -->
            <% end %> <!-- eventsのeachメソッド終わり -->
        </div>
    </div>
</div>

<!-- 夜席の表示 -->
<div class="card col-12 yose-yoru">
    <div class="card-body text-box">
        <div class="card-text comedians">
            <% events.each do |event| %>
              <% if (event.start_time == Date.today) && (event.theater_id == 3) && (event.daynight_id == 2) %>
                <p class="yose-title"><%= event.theater.name %></p>
                <p class="yose-title"><%= event.daynight.name %>席</p>
                <%# 出演者の名前 %>
                <% event.event_comedians.each do |event_comedian| %>
                  <% if event_comedian.comedian_id != 0 %>
                    <div class="wood">
                      <%= image_tag("wood.jpg", class: "img-fluid") %>
                      <p class="comedian-name">
                        一．<%= event_comedian.comedian.name %>
                      </p>
                    </div>
                  <% end %>
                <% end %> <!-- 芸名表示のeachメソッド終わり -->
                <!-- いいねボタン表示 -->
                <% if user_signed_in? %>
                  <% if current_user.already_reaction_liked?(event) %>
                   <%= button_to 'いいね削除', event_reaction_like_path(event, current_user), method: :delete, class:"mr-1" %>
                  <% else %>
                   <%= button_to 'いいね', event_reaction_likes_path(event), method: :post, class:"mr-1" %>
                  <% end %>
                  <!-- 管理者のみ編集・削除ボタン -->
                  <% if current_user.admin == true %>
                    <%= button_to '編集', edit_admin_event_path(event), method: :get, class:"mr-1" %>
                    <%= button_to '削除', admin_event_path(event), method: :delete, class:"mr-1" %>
                  <% end %>
                <% end %>
              <% end %> <!-- 夜席のif指定終わり -->
            <% end %> <!-- eventsのeachメソッド終わり -->
        </div>
    </div>
</div>

<div class="info col-12 ca-twitter">
  <!-- カレンダー -->
  <div class="card calendar">
    <div class="card-body  order-md-1">
        <div class="card-text text-dark calendar-text">
            <%= month_calendar events: @events do |date, events| %>
              <p><%= date.day %></p>
              <% events.each do |event| %>
                <% if event.daynight_id == 1 %>
                  <% daynight = "昼" %>
                <% else %>
                  <% daynight = "夜" %>
                <% end %>

                <% dd = event.start_time.day %>
                <% if event.theater_id == 3 %>
                  <% if dd > 0 && dd < 11 %>
                      <p id="event"><%= link_to "上席:#{daynight}", event_path(event.id) %></p>
                  <% elsif dd > 10 && dd < 21 %>
                      <p id="event"><%= link_to "中席:#{daynight}", event_path(event.id) %></p>
                  <% elsif dd > 20 && dd < 31 %>
                      <p id="event"><%= link_to "下席:#{daynight}", event_path(event.id) %></p>
                  <% else %>
                    <p id="event"><%= link_to "余一会:#{daynight}", event_path(event.id) %></p>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
        </div>
    </div>
  </div>

  <!-- MAP -->
  <div class="card bg-transparent map">
      <div class="card-body">
            <div class="map-in order-md-3" id="map_03">
              <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["GOOGLE_MAP_API_KEY"] %>"></script>
            </div>
      </div>
  </div>

  <!-- Twitter -->
  <div class="card bg-transparent twitter">
      <div class="card-body">
          <div class="card-text text-dark">
            <div class="twitter-in order-md-2">
              <a class="twitter-timeline" data-lang="ja" data-height="850px" data-theme="dark" href="https://twitter.com/asakusa_engei?ref_src=twsrc%5Etfw">Tweets by suehirotei</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
            </div>
          </div>
      </div>
  </div>
</div>

app/views/events/_asakusa_show.html.erb
<!-- 昼席の表示 -->
<div class="card col-12 yose-hiru">
    <div class="card-body text-box">
        <div class="card-text comedians">
            <% shows.each do |event| %>
              <% if (event.start_time == selectday) && (event.theater_id == 3) && (event.daynight_id == 1) %>
                <p class="yose-title"><%= event.theater.name %></p>
                <p class="yose-title"><%= event.daynight.name %>席</p>
                <%# 出演者の名前 %>
                <% event.event_comedians.each do |event_comedian| %>
                  <% if event_comedian.comedian_id != 0 %>
                    <div class="wood">
                      <%= image_tag("wood.jpg", class: "img-fluid") %>
                      <p class="comedian-name">
                        一．<%= event_comedian.comedian.name %>
                      </p>
                    </div>
                  <% end %>
                <% end %> <!-- 芸名表示のeachメソッド終わり -->
                <!-- いいねボタン表示 -->
                <% if user_signed_in? %>
                  <% if current_user.already_reaction_liked?(event) %>
                   <%= button_to 'いいね削除', event_reaction_like_path(event, current_user), method: :delete, class:"mr-1" %>
                  <% else %>
                   <%= button_to 'いいね', event_reaction_likes_path(event), method: :post, class:"mr-1" %>
                  <% end %>
                  <!-- 管理者のみ編集・削除ボタン -->
                  <% if current_user.admin == true %>
                    <%= button_to '編集', edit_admin_event_path(event), method: :get, class:"mr-1" %>
                    <%= button_to '削除', admin_event_path(event), method: :delete, class:"mr-1" %>
                  <% end %>
                <% end %>
              <% end %> <!-- 昼席のif指定終わり -->
            <% end %> <!-- eventsのeachメソッド終わり -->
        </div>
    </div>
</div>

<!-- 夜席の表示 -->
<div class="card col-12 yose-yoru">
    <div class="card-body text-box">
        <div class="card-text comedians">
            <% shows.each do |event| %>
              <% if (event.start_time == selectday) && (event.theater_id == 3) && (event.daynight_id == 2) %>
                 <p class="yose-title"><%= event.theater.name %></p>
                <p class="yose-title"><%= event.daynight.name %>席</p>
                <%# 出演者の名前 %>
                <% event.event_comedians.each do |event_comedian| %>
                  <% if event_comedian.comedian_id != 0 %>
                    <div class="wood">
                      <%= image_tag("wood.jpg", class: "img-fluid") %>
                      <p class="comedian-name">
                        一．<%= event_comedian.comedian.name %>
                      </p>
                    </div>
                  <% end %>
                <% end %> <!-- 芸名表示のeachメソッド終わり -->
                <!-- いいねボタン表示 -->
                <% if user_signed_in? %>
                  <% if current_user.already_reaction_liked?(event) %>
                   <%= button_to 'いいね削除', event_reaction_like_path(event, current_user), method: :delete, class:"mr-1" %>
                  <% else %>
                   <%= button_to 'いいね', event_reaction_likes_path(event), method: :post, class:"mr-1" %>
                  <% end %>
                  <!-- 管理者のみ編集・削除ボタン -->
                  <% if current_user.admin == true %>
                    <%= button_to '編集', edit_admin_event_path(event), method: :get, class:"mr-1" %>
                    <%= button_to '削除', admin_event_path(event), method: :delete, class:"mr-1" %>
                  <% end %>
                <% end %>
              <% end %> <!-- 夜席のif指定終わり -->
            <% end %> <!-- eventsのeachメソッド終わり -->
        </div>
    </div>
</div>

<div class="info col-12 ca-twitter">
  <!-- カレンダー -->
  <div class="card calendar">
    <div class="card-body  order-md-1">
        <div class="card-text text-dark calendar-text">
            <%= month_calendar events: @events do |date, events| %>
              <p><%= date.day %></p>
              <% events.each do |event| %>
                <% if event.daynight_id == 1 %>
                  <% daynight = "昼" %>
                <% else %>
                  <% daynight = "夜" %>
                <% end %>

                <% dd = event.start_time.day %>
                <% if event.theater_id == 3 %>
                  <% if dd > 0 && dd < 11 %>
                      <p id="event"><%= link_to "上席:#{daynight}", event_path(event.id) %></p>
                  <% elsif dd > 10 && dd < 21 %>
                      <p id="event"><%= link_to "中席:#{daynight}", event_path(event.id) %></p>
                  <% elsif dd > 20 && dd < 31 %>
                      <p id="event"><%= link_to "下席:#{daynight}", event_path(event.id) %></p>
                  <% else %>
                    <p id="event"><%= link_to "余一会:#{daynight}", event_path(event.id) %></p>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
        </div>
    </div>
  </div>

  <!-- MAP -->
  <div class="card bg-transparent map">
      <div class="card-body">
            <div class="map-in order-md-3" id="map_03">
              <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["GOOGLE_MAP_API_KEY"] %>"></script>
            </div>
      </div>
  </div>

  <!-- Twitter -->
  <div class="card bg-transparent twitter">
      <div class="card-body">
          <div class="card-text text-dark">
            <div class="twitter-in order-md-2">
              <a class="twitter-timeline" data-lang="ja" data-height="850px" data-theme="dark" href="https://twitter.com/asakusa_engei?ref_src=twsrc%5Etfw">Tweets by suehirotei</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
            </div>
          </div>
      </div>
  </div>
</div>, class:"mr-1"

app/views/events/_ikebukuro.html.erb
<!-- 昼席の表示 -->
<div class="card col-12 yose-hiru">
    <div class="card-body text-box">
        <div class="card-text comedians">
            <% events.each do |event| %>
              <% if (event.start_time == Date.today) && (event.theater_id == 2) && (event.daynight_id == 1) %>
                <p class="yose-title"><%= event.theater.name %></p>
                <p class="yose-title"><%= event.daynight.name %>席</p>
                <%# 出演者の名前 %>
                <% event.event_comedians.each do |event_comedian| %>
                  <% if event_comedian.comedian_id != 0 %>
                    <div class="wood">
                      <%= image_tag("wood.jpg", class: "img-fluid") %>
                      <p class="comedian-name">
                        一．<%= event_comedian.comedian.name %>
                      </p>
                    </div>
                  <% end %>
                <% end %> <!-- 芸名表示のeachメソッド終わり -->
                <!-- いいねボタン表示 -->
                <% if user_signed_in? %>
                  <% if current_user.already_reaction_liked?(event) %>
                   <%= button_to 'いいね削除', event_reaction_like_path(event, current_user), method: :delete, class:"mr-1" %>
                  <% else %>
                   <%= button_to 'いいね', event_reaction_likes_path(event), method: :post, class:"mr-1" %>
                  <% end %>
                  <!-- 管理者のみ編集・削除ボタン -->
                  <% if current_user.admin == true %>
                    <%= button_to '編集', edit_admin_event_path(event), method: :get, class:"mr-1" %>
                    <%= button_to '削除', admin_event_path(event), method: :delete, class:"mr-1" %>
                  <% end %>
                <% end %>
              <% end %> <!-- 昼席のif指定終わり -->
            <% end %> <!-- eventsのeachメソッド終わり -->
        </div>
    </div>
</div>

<!-- 夜席の表示 -->
<div class="card col-12 yose-yoru">
    <div class="card-body text-box">
        <div class="card-text comedians">
            <% events.each do |event| %>
              <% if (event.start_time == Date.today) && (event.theater_id == 2) && (event.daynight_id == 2) %>
                <p class="yose-title"><%= event.theater.name %></p>
                <p class="yose-title"><%= event.daynight.name %>席</p>
                <%# 出演者の名前 %>
                <% event.event_comedians.each do |event_comedian| %>
                  <% if event_comedian.comedian_id != 0 %>
                    <div class="wood">
                      <%= image_tag("wood.jpg", class: "img-fluid") %>
                      <p class="comedian-name">
                        一．<%= event_comedian.comedian.name %>
                      </p>
                    </div>
                  <% end %>
                <% end %> <!-- 芸名表示のeachメソッド終わり -->
               <!-- いいねボタン表示 -->
                <% if user_signed_in? %>
                  <% if current_user.already_reaction_liked?(event) %>
                   <%= button_to 'いいね削除', event_reaction_like_path(event, current_user), method: :delete, class:"mr-1" %>
                  <% else %>
                   <%= button_to 'いいね', event_reaction_likes_path(event), method: :post, class:"mr-1" %>
                  <% end %>
                  <!-- 管理者のみ編集・削除ボタン -->
                  <% if current_user.admin == true %>
                    <%= button_to '編集', edit_admin_event_path(event), method: :get, class:"mr-1" %>
                    <%= button_to '削除', admin_event_path(event), method: :delete, class:"mr-1" %>
                  <% end %>
                <% end %>
              <% end %> <!-- 夜席のif指定終わり -->
            <% end %> <!-- eventsのeachメソッド終わり -->
        </div>
    </div>
</div>

<div class="info col-12 ca-twitter">
  <!-- カレンダー -->
  <div class="card calendar">
    <div class="card-body  order-md-1">
        <div class="card-text text-dark calendar-text">
            <%= month_calendar events: @events do |date, events| %>
              <p><%= date.day %></p>
              <% events.each do |event| %>
                <% if event.daynight_id == 1 %>
                  <% daynight = "昼" %>
                <% else %>
                  <% daynight = "夜" %>
                <% end %>

                <% dd = event.start_time.day %>
                <% if event.theater_id == 2 %>
                  <% if dd > 0 && dd < 11 %>
                      <p id="event"><%= link_to "上席:#{daynight}", event_path(event.id) %></p>
                  <% elsif dd > 10 && dd < 21 %>
                      <p id="event"><%= link_to "中席:#{daynight}", event_path(event.id) %></p>
                  <% elsif dd > 20 && dd < 31 %>
                      <p id="event"><%= link_to "下席:#{daynight}", event_path(event.id) %></p>
                  <% else %>
                    <p id="event"><%= link_to "余一会:#{daynight}", event_path(event.id) %></p>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
        </div>
    </div>
  </div>

  <!-- MAP -->
  <div class="card bg-transparent map">
      <div class="card-body">
            <div class="map-in order-md-3" id="map_02">
              <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["GOOGLE_MAP_API_KEY"] %>"></script>
            </div>
      </div>
  </div>

  <!-- Twitter -->
  <div class="card bg-transparent twitter">
      <div class="card-body">
          <div class="card-text text-dark">
            <div class="twitter-in order-md-2">
               <a href="https://twitter.com/intent/tweet?button_hashtag=池袋演芸場&ref_src=twsrc%5Etfw" class="twitter-hashtag-button" data-lang="ja" data-height="1000px" data-theme="dark" data-show-count="false">Tweet #池袋演芸場</a>
               <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
            </div>
          </div>
      </div>
  </div>
</div>